'use client';

import { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import './globals.css';
import { useEffect } from 'react';
import { initPosthog } from '@/lib/posthog';
import posthog from 'posthog-js';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  useEffect(() => {
    initPosthog();
    posthog.capture('pageview');
    posthog.capture('test_event', { property: 'value' }); // test event
  }, []);

  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${GeistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
